services:
  db:
    image: container-registry.oracle.com/database/free:23.8.0.0
    hostname: database
    ports:
      - 1522:1521
    environment:
      - ORACLE_PWD=pwd
      - DBHOST=database
    volumes:
      - ./oracle_oradata/:/opt/oracle/oradata
  ords:
    image: container-registry.oracle.com/database/ords:25.2.0
    ports:
      - 8081:8080
    environment:
      - DBHOST=database
      - DBPORT=1521
      - DBSERVICENAME=FREEPDB1
      - ORACLE_PWD=pwd
    volumes:
      - ./ords_config/:/etc/ords/config
      - ./apex/:/opt/oracle/apex
    depends_on:
      db:
        condition: service_healthy